<?php

namespace Tests\Feature\Api\V1;

use App\Models\Project;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ProjectTest extends TestCase
{
    use RefreshDatabase;

    public function test_can_get_all_projects()
    {
        Project::factory()->count(3)->create();

        $response = $this->getJson('/api/v1/projects');

        $response->assertOk();
        $response->assertJsonCount(3);
    }

    public function test_can_create_a_project()
    {
        $data = [
            'display_name' => 'Test Project',
            'project_id' => 'test-project-id',
            'project_key' => 'test-project-key',
        ];

        $response = $this->postJson('/api/v1/projects', $data);

        $response->assertCreated();
        $response->assertJsonFragment(['display_name' => $data['display_name']]);
        $this->assertDatabaseHas('projects', ['display_name' => $data['display_name']]);
    }

    public function test_can_create_a_project_with_autogenerated_keys()
    {
        $data = [
            'display_name' => 'Test Project 2',
        ];

        $response = $this->postJson('/api/v1/projects', $data);

        $response->assertCreated();
        $response->assertJsonFragment(['display_name' => $data['display_name']]);
        $this->assertDatabaseHas('projects', ['display_name' => $data['display_name']]);

        $project = Project::where('display_name', $data['display_name'])->first();
        $this->assertNotNull($project->project_id);
        $this->assertNotNull($project->project_key);
    }

    public function test_can_get_a_project()
    {
        $project = Project::factory()->create();

        $response = $this->getJson("/api/v1/projects/{$project->id}");

        $response->assertOk();
        $response->assertJsonFragment(['id' => $project->id]);
    }

    public function test_can_update_a_project()
    {
        $project = Project::factory()->create();

        $data = [
            'display_name' => 'Updated Project Name',
        ];

        $response = $this->putJson("/api/v1/projects/{$project->id}", $data);

        $response->assertOk();
        $response->assertJsonFragment($data);
        $this->assertDatabaseHas('projects', $data);
    }

    public function test_can_sync_project_constants()
    {
        $project = Project::factory()->create();
        $existingConstant = $project->projectConstants()->create(['key' => 'existing', 'data' => 'data']);

        $data = [
            'project_constants' => [
                ['id' => $existingConstant->id, 'key' => 'existing', 'data' => 'updated data'],
                ['key' => 'new', 'data' => 'new data'],
            ],
        ];

        $response = $this->putJson("/api/v1/projects/{$project->id}", $data);

        $response->assertOk();
        $this->assertDatabaseHas('project_constants', ['id' => $existingConstant->id, 'data' => 'updated data']);
        $this->assertDatabaseHas('project_constants', ['key' => 'new', 'data' => 'new data']);
    }

    public function test_can_sync_project_header_texts()
    {
        $project = Project::factory()->create();
        $existingText = $project->projectHeaderTexts()->create(['data' => 'existing text']);

        $data = [
            'project_header_texts' => [
                ['id' => $existingText->id, 'data' => 'updated text'],
                ['data' => 'new text'],
            ],
        ];

        $response = $this->putJson("/api/v1/projects/{$project->id}", $data);

        $response->assertOk();
        $this->assertDatabaseHas('project_header_texts', ['id' => $existingText->id, 'data' => 'updated text']);
        $this->assertDatabaseHas('project_header_texts', ['data' => 'new text']);
    }

    public function test_can_sync_project_time_servers()
    {
        $project = Project::factory()->create();
        $existingServer = $project->projectTimeServers()->create(['data' => 'time.nist.gov']);

        $data = [
            'project_time_servers' => [
                ['id' => $existingServer->id, 'data' => 'time.google.com'],
                ['data' => 'time.windows.com'],
            ],
        ];

        $response = $this->putJson("/api/v1/projects/{$project->id}", $data);

        $response->assertOk();
        $this->assertDatabaseHas('project_time_servers', ['id' => $existingServer->id, 'data' => 'time.google.com']);
        $this->assertDatabaseHas('project_time_servers', ['data' => 'time.windows.com']);
    }

    public function test_can_delete_a_project()
    {
        $project = Project::factory()->create();

        $response = $this->deleteJson("/api/v1/projects/{$project->id}");

        $response->assertNoContent();
        $this->assertDatabaseMissing('projects', ['id' => $project->id]);
    }

    public function test_creating_a_project_creates_default_version_and_variation()
    {
        $data = [
            'display_name' => 'Test Project',
            'project_id' => 'test-project-id',
            'project_key' => 'test-project-key',
        ];

        $response = $this->postJson('/api/v1/projects', $data);

        $response->assertCreated();
        $project = Project::first();

        $this->assertCount(1, $project->versions);
        $this->assertEquals('Default', $project->versions->first()->display_name);

        $this->assertCount(1, $project->variations);
        $this->assertEquals('Default', $project->variations->first()->display_name);
    }
}
